"""empty message

Revision ID: 450cc9808cb8
Revises: a6f8ea48c383
Create Date: 2024-10-03 10:38:27.347018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450cc9808cb8'
down_revision = 'a6f8ea48c383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_gain_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_gain_percent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('avg_cost_per_share', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('avg_cost_per_share')
        batch_op.drop_column('total_gain_percent')
        batch_op.drop_column('total_gain_value')

    # ### end Alembic commands ###
